_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/plasticine/standard/td3_dmc_vanilla_multi.py
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 24
                - 34
                - 35
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 256
buffer_size:
    value: 1000000
capture_video:
    value: false
cuda:
    value: true
env_id:
    value: Hopper-v4
env_ids:
    value:
        - dog_stand
        - dog_walk
        - dog_trot
        - dog_run
        - dog_fetch
exp_name:
    value: td3_dmc_vanilla_multi
exploration_noise:
    value: 0.1
gamma:
    value: 0.99
hf_entity:
    value: ""
learning_rate:
    value: 0.0003
learning_starts:
    value: 25000
noise_clip:
    value: 0.5
num_envs:
    value: 1
plasticity_eval_interval:
    value: 1000
plasticity_eval_size:
    value: 1000
policy_frequency:
    value: 2
policy_noise:
    value: 0.2
save_model:
    value: false
seed:
    value: 1
tau:
    value: 0.005
torch_deterministic:
    value: true
total_timesteps:
    value: 1000
track:
    value: true
upload_model:
    value: false
wandb_entity:
    value: null
wandb_project_name:
    value: cleanRL
